# Generated by Django 5.1.2 on 2024-10-14 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chama",
            name="no_of_members",
        ),
        migrations.AddField(
            model_name="chama",
            name="registration_no",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("chamaMember", "Chama Member"),
                    ("appAdmin", "App Admin"),
                    ("chamaAdmin", "Chama Admin"),
                ],
                default="chamaMember",
                max_length=20,
            ),
        ),
    ]
