# Generated by Django 5.1.2 on 2024-10-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_chamamembership_is_admin_alter_customuser_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chama",
            name="admin",
        ),
    ]
