// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3T18BiYrR33gFPiygR6F4Joeq4nVZ-5Y',
    appId: '1:676569728670:web:d345a9a4baab497b575d8f',
    messagingSenderId: '676569728670',
    projectId: 'awachamapp',
    authDomain: 'awachamapp.firebaseapp.com',
    storageBucket: 'awachamapp.appspot.com',
    measurementId: 'G-XELXYNBVBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZVxUw0TcaldSqsbWhCazbiHe2zvwh1c',
    appId: '1:676569728670:android:1549a7085555f266575d8f',
    messagingSenderId: '676569728670',
    projectId: 'awachamapp',
    storageBucket: 'awachamapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsGdd4Nobu4vawh01lXVn0s-8mLxgxk-0',
    appId: '1:676569728670:ios:ab590e99d7beeb84575d8f',
    messagingSenderId: '676569728670',
    projectId: 'awachamapp',
    storageBucket: 'awachamapp.appspot.com',
    iosBundleId: 'com.example.awachamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsGdd4Nobu4vawh01lXVn0s-8mLxgxk-0',
    appId: '1:676569728670:ios:ab590e99d7beeb84575d8f',
    messagingSenderId: '676569728670',
    projectId: 'awachamapp',
    storageBucket: 'awachamapp.appspot.com',
    iosBundleId: 'com.example.awachamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3T18BiYrR33gFPiygR6F4Joeq4nVZ-5Y',
    appId: '1:676569728670:web:b564804463241fff575d8f',
    messagingSenderId: '676569728670',
    projectId: 'awachamapp',
    authDomain: 'awachamapp.firebaseapp.com',
    storageBucket: 'awachamapp.appspot.com',
    measurementId: 'G-JFG7ZNP7TM',
  );
}
